### ISSUE TITLE
Water in the Nether

### ISSUE THREAD

**Issue by EpicBirb** [ICY105/Mechanization#157] opened 2022-01-21 19:02 UTC
My friend told me that he/she made water in the nether by blowing up (tnt) Tin Ore. Is this supposed to be intentional?

**Comment by LudwigBooysen** [comment] 2022-08-27 16:45
questionable, first how did they even get Tin Ore in the nether? and secondly with my testing I can not even seem to explode the Tin Ore. Please help maybe I can provide with a answer, because this issue makes me instantly think of the item drop or maybe even something to do with explosion resistance.

**Comment by nekonomura** [comment] 2022-10-23 06:16
Attempted tin ore blasting in the Nether, but was hampered by tin ore's blast resistance. Next, I tried destroying it with a pickaxe. But no water came out. Then I tried to destroy it in creative mode. Then water came out. (This result is from a tin ore mined with a Silk Touch pickaxe and placed in the Nether.) For comparison, I tried the same in a dimension other than the Nether and found that when destroyed in creative mode, tin ore water came out.

**Comment by EpicBirb** [comment] 2022-10-25 21:53
> Questionable, first how did they even get Tin Ore in the nether? and secondly with my testing I can not even seem to explode the Tin Ore. Please help maybe I can provide with a answer, because this issue makes me instantly think of the item drop or maybe even something to do with explosion resistance.

honestly I have no idea but they sent a screen shot to me which kinda surprised me
Oh and if you are asking for the screenshot, I don't think I can find it anymore lol

**Comment by ICY105** [comment] 2023-06-12 00:09
Appears to be duplicate of #92

**Closed by ICY105** 2023-06-12 00:09 UTC
Labels: bug
